### ISSUE TITLE
Auto Crafter Problems

### ISSUE THREAD

**Issue by SpyceTewan** [Da-Technomancer/Essentials#24]
The auto crafter has a couple of problems.

First of all, it eats buckets and similar items that have a remaining item when crafted.  
Secondly, its inventory only doesn't accept two stacks of the same item. This is actually a pretty cool feature, but this means that crafting recipes that use more than one unstackable items are impossible. Cakes for example.

**Comment by Da-Technomancer** [comment]
*Fixed container items being lost by the autocrafter- they now get put into the input slots
*Instead of the autocrafter only accepting 1 stack of each item type, it now accepts 1 stack PER ITEM USED IN THE RECIPE; For example, the stone pickaxe recipe now allows 3 stacks cobble and 2 stacks sticks into the input slots
*Automation (hoppers, pipes, etc) can now remove any item from the input slots that aren't allowed to be there (AKA, buckets that were put in there when crafting cakes)

**Comment by Da-Technomancer** [comment]
Fixed in 2.6.4, available here: https://www.curseforge.com/minecraft/mc-mods/essentials/files/2836391
