### ISSUE TITLE
Auto crafter inventory does not accept items on all slots

### ISSUE THREAD

**Issue by winsrp** [Da-Technomancer/Essentials#57]
If I want to auto craft sticks, for example, I can only fill inv slots 1 and 2, if I auto craft, crafting tables, I can only fill slots 1 to 4, if I auto craft, fences, I can only fill slots 1 to 6 of the autocrafter inventory.

Seems like the inventory is linked to the items on the recipe, which seems kind of odd.

As a work around, I putt all wood into the crafting grid, then fill the inv with the materials I need, then I remove the wood and put the right items in case the recipe doesn't take all 9 crafting grid slots.

tx

**Comment by Da-Technomancer** [comment]
As the book explains, this is intended behavior. You can only fill as many input slots with an ingredient as there are instances of that item used in the recipe. 
This is so that if you're crafting a recipe with multiple ingredients (for example, stone pickaxes), you don't have to worry about the input being completely filled with sticks, as three slots are reserved for cobblestone.

**Comment by winsrp** [comment]
can we have reserved slots only on the ones that need to be reserved? and the other ones are free for excess items
