### ISSUE TITLE
Counter and Latch Circuits

### ISSUE THREAD

**Issue by Random-Scientist** [Da-Technomancer/Essentials#63]
Suggestions:
Two new Circuit Plate variants:

Counter Circuit: Stores value and increments upwards. On the rising edge of a circuit pulse from the back, the value increments upwards from 0 by one. A pulse to a side resets the counter to zero, and the output is from the front

Register Circuit:
Passes input through from back to front, UNLESS a side input has a value greater than 0, in which case the output is 'latched' to the input value at that moment.

Justification:
In my experiments, I realized that there are no options for fully circuit-enabled memory that do not require player input of some sort. This got pretty annoying on several occasions, especially in the case of complex puzzles like gateway dialing (From Crossroads). Anyhow, this issue is more of a loose idea than a specific request, feel free to disregard all of it if you have a better solution to the lack of memory.

**Comment by Da-Technomancer** [comment]
The latest commit 6d1dbe9 added a new 'Counter Circuit', which doesn't do exactly what you described (it outputs the sum of the value of all input pulses instead of the number of input pulses), but can be used to build both a 'register circuit' equivalent and a 'counter circuit' (your version) equivalent. 

I'm considering this issue closed, as it is currently all in the way of memory circuits I am planning on adding.
